base_url = "https://resysto.io"
title = "resysto"
description = "Central Cyber Resilience and Data Protection platform to govern and manage cybersecurity and privacy."
default_language = "en"
compile_sass = false
minify_html = true
generate_sitemap = true
build_search_index = true
generate_feeds = true

# Taxonomies for the default language (English)
taxonomies = [
  { name = "tags", rss = true },
  { name = "audience", rss = false },
  { name = "content_priority", rss = false },
  { name = "layout_type", rss = false },
]

# Language configurations
# English is the default language, so its config goes at the base level
# Italian is the secondary language
[languages.it]
generate_feeds = true
build_search_index = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "audience", rss = false },
  { name = "content_priority", rss = false },
  { name = "layout_type", rss = false },
]

# Translations for UI elements
[translations]
# English translations (default language)
home = "Home"
features = "Features"
roadmap = "Roadmap"
partners = "Partners"
blog = "Blog"
about = "About"
access = "Access"
contact = "Contact"
privacy = "Privacy"
terms = "Terms"
language = "Language"

[languages.it.translations]
# Italian translations
home = "Home"
features = "Caratteristiche"
roadmap = "Roadmap"
partners = "Partner"
blog = "Blog"
about = "Chi Siamo"
access = "Accesso"
contact = "Contatto"
privacy = "Privacy"
terms = "Termini"
language = "Lingua"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
site_name = "resysto"
og_type = "website"
twitter_card = "summary_large_image"
twitter_site = "@agorasecurity"
twitter_creator = "@agorasecurity"
default_image = "/images/og-default.svg"
canonical_base = "https://resysto.io"
company_name = "Agora Security"
contact_email = "info@agorasecurity.it"

# Layout configuration
default_layout_type = "content_heavy"
default_content_density = "balanced"
default_audience = ["ciso", "cio", "ceo"]
show_key_concepts = true

# Performance and accessibility
performance_budget = 500
accessibility_compliance = "wcag_2_1_aa"
enable_audience_targeting = true
enable_adaptive_layouts = true

# Content thresholds
content_thresholds = { short = 500, medium = 1500, long = 3000 }

# SEO and meta
enable_structured_data = true
enable_open_graph = true
enable_twitter_cards = true

[extra.nav]
items = [
  { name = "Features", url = "/features" },
  { name = "Roadmap", url = "/roadmap" },
  { name = "Partners", url = "/partners" },
  { name = "Blog", url = "/blog" },
  { name = "About", url = "/about" },
  { name = "Access", url = "/access" },
]
