base_url = "https://resysto.io/" # updated to new domain
title = "resysto"
description = "Central Cyber Resilience and Data Protection platform to govern and manage cybersecurity and privacy."
default_language = "en"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true
generate_robots_txt = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "audience", rss = false },
  { name = "content_priority", rss = false },
  { name = "layout_type", rss = false },
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
site_name = "resysto"
og_type = "website"
twitter_card = "summary_large_image"
twitter_site = "@agorasecurity"
twitter_creator = "@agorasecurity"
default_image = "/images/og-default.svg"
canonical_base = "https://resysto.io"
company_name = "Agora Security"
contact_email = "info@agorasecurity.it"

# Layout configuration
default_layout_type = "content_heavy"
default_content_density = "balanced"
default_audience = ["ciso", "cio", "ceo"]
show_key_concepts = true

# Performance and accessibility
performance_budget = 500
accessibility_compliance = "wcag_2_1_aa"
enable_audience_targeting = true
enable_adaptive_layouts = true

# Content thresholds
content_thresholds = { short = 500, medium = 1500, long = 3000 }

# SEO and meta
enable_structured_data = true
enable_open_graph = true
enable_twitter_cards = true

[extra.nav]
items = [
  { name = "Features", url = "/features/" },
  { name = "Roadmap", url = "/roadmap/" },
  { name = "Partners", url = "/partners/" },
  { name = "Blog", url = "/blog/" },
  { name = "About", url = "/about/" },
  { name = "Access", url = "/access/" },
]

