name: Build and deploy GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps and build CSS
        run: |
          npm ci
          npx tailwindcss -i ./assets/css/main.css -o ./static/css/main.css --minify

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token for same-repo publishing
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
